#!/bin/bash


source `dirname $0`/create $@

set -x

ssh $remoteUrl drush -r $remotePath sql-dump > dump.sql
drush sqlq "source dump.sql"
rsync --delete --progress -a $remoteUrl:$remotePath/sites/default/files sites/default
drush cc all

set +x
