#!/bin/bash

NO_ARGS=0
USAGE="`basename $0` [-u dburl] [-n accountname] [-p accountpass] [-m mysqlroot] [-t target] manifest"

if [ $# -eq "$NO_ARGS" ]  # Script invoked with no command-line args?
then
    echo $USAGE
    cat <<EOF
Clones a remote drupal site providing it has been created using a make file
and profile.

The only mandatory parameter is the manifest location.  This must be a valid
URL.

-u  The DB url to create for this site, mysql://name:passwd@host/dbname this
    will default to the mysql://manifest:manifest@localhost/manifest where
    manifest is the basename of the mandatory parameter.
-n  Account name for the admin account, defaults to superadmin
-p  Password for the admin account, defaults to password
-m  The mysql root user:password, this will default to root:$MYSQL_ROOTPASS
-t  The deployment target locally, defaults to minifest

Sample manifest file:

makefile=http://192.168.21.27/manifest/wightlocations.make
remoteUrl=root@192.168.21.44
remotePath=/home/wightlocations/www/NeonTABS/demosite
profile=neontabs_profile
sitename="White Locations"

N.B. No spaces between names, equals and values.  Quotes around sitename

EOF
    exit 1
fi

while getopts "u:n:p:m:t:" options; do
    case $options in
        u)  dburl="$OPTARG";;
        n)  accountname="$OPTARG";;
        p)  accountpass="$OPTARG";;
        m)  mysqlroot="$OPTARG";;
        t)  target="$OPTARG";;
    esac
done

shift $((OPTIND-1))
manifest=$1
_manifest=`basename $manifest .manifest`

if [ -z $manifest ]
then
    echo $USAGE
    exit 1
fi

if [ -z "$dburl" ]; then
    dburl="mysql://$_manifest:$_manifest@localhost/$_manifest"
fi

if [ -z "$accountname" ]; then
    accountname="superadmin"
fi

if [ -z "$accountpass" ]; then
    accountpass="password"
fi

if [ -z "$mysqlroot" ]; then
    mysqlrootuser=root
    mysqlrootpass=$MYSQL_ROOTPASS
else
    mysqlrootuser=`echo $mysqlroot | awk -F: '{print $1}'`
    mysqlrootpass=`echo $mysqlroot | awk -F: '{print $2}'`
fi

if [ -z "$target" ]; then
    target=$_manifest
fi

rm $_manifest
wget -q $manifest
source $_manifest.manifest

drush make $makefile $target
cd $target
drush -y si $profile --db-url=$dburl --account-name=$accountname --account-pass=$accountpass --db-su=$mysqlrootuser --db-su-pw=$mysqlrootpass --site-name=\"$sitename\"
compass compile sites/all/themes/neontabs
compass compile sites/all/themes/ntwl
ssh $remoteUrl drush -r $remotePath sql-dump > dump.sql
drush sqlq "source dump.sql"
rsync --delete --progress -a $remoteUrl:$remotePath/sites/default/files sites/default
echo "If you are mounting this site on a URL other than the site root then you will"
echo "need to change the BaseUrl in the .htaccess file, $target/.htaccess"
drush cc all
