#!/bin/bash

source `dirname $0`/processargs $@

# echo -e "Remote Manifest:\t${manifest}";
# echo -e "Local Manifest:\t\t${_manifest}";
# echo -e "DB Url:\t\t\t${dburl}";
# echo -e "Account name:\t\t${accountname}";
# echo -e "Account password:\t${accountpass}";
# echo -e "Mysql root username:\t${mysqlrootuser}";
# echo -e "Mysql root password:\t${mysqlrootpass}";
# echo -e "Target dir:\t\t${target}";

set -x

rm -f $_manifest
wget -q $manifest
source $_manifest.manifest

drush make $makefile $target
cd $target
drush -y si $profile --db-url=$dburl --account-name=$accountname --account-pass=$accountpass --db-su=$mysqlrootuser --db-su-pw=$mysqlrootpass --site-name=\"$sitename\"

compass compile sites/all/themes/neontabs
compass compile sites/all/themes/ntwl

drush cc all

set +x
