#!/bin/bash

source `dirname $0`/processargs $@

if [ ! -z "$verbose" ]; then
    echo -e "Remote Manifest:\t${manifest}";
    echo -e "Local Manifest:\t\t${_manifest}";
    echo -e "DB Url:\t\t\t${dburl}";
    echo -e "Account name:\t\t${accountname}";
    echo -e "Account password:\t${accountpass}";
    echo -e "Mysql root username:\t${mysqlrootuser}";
    echo -e "Mysql root password:\t${mysqlrootpass}";
    echo -e "Target dir:\t\t${target}";

    set -x

fi

rm -f $_manifest
wget -q $manifest
source $_manifest.manifest

drush make $wc --force-gitinfofile $makefile $target
CWD=`pwd`
cd $target
drush -y si $profile --db-url=$dburl --account-name=$accountname --account-pass=$accountpass --db-su=$mysqlrootuser --db-su-pw=$mysqlrootpass --site-name="${sitename}"

for x in `find sites/all/themes -type d -maxdepth 1`; do
    cd $x
    compass compile
    cd -
done

drush cc all
drush en -y $settings_module

cd $CWD

if [ ! -z "$verbose" ]; then
    set +x
fi
