#!/bin/bash

BRANDCODE=$1
BUILD_NUMBER=$2
FULLNAME=$3
BRANCH='master'

BUILD_TARGET=$FULLNAME.$BUILD_NUMBER
DEPLOY_TARGET=/home/cottage_staging/www/$FULLNAME/jenkins/$BUILD_NUMBER

ntdc -v -m root:b191wkm -u mysql://ci_$BRANDCODE:ci_$BRANDCODE@localhost/ci_$BRANDCODE -t $BUILD_TARGET http://cottage.neontribe.org/manifest/$FULLNAME.manifest
mkdir -p `dirname $DE$DEPLOY_TARGET`
cp -r $BUILD_TARGET $DEPLOY_TARGET
sudo /usr/local/bin/ntresetperms -y jenkins jenkins www-data www-data -p $DEPLOY_TARGET
ln -sf $DEPLOY_TARGET `dirname $DE$DEPLOY_TARGET`/$BRANCH
