#!/bin/bash

NO_ARGS=0
USAGE="`basename $0` [-u dburl] [-n accountname] [-p accountpass] [-m mysqlroot] [-t target] manifest"

# exit on errors, for CI
set -e

if [ $# -eq "$NO_ARGS" ]  # Script invoked with no command-line args?
then
    echo $USAGE
    cat <<EOF
Clones a remote drupal site providing it has been created using a make file
and profile.

The only mandatory parameter is the manifest location.  This must be a valid
URL.

-u  The DB url to create for this site, mysql://name:passwd@host/dbname this
    will default to the mysql://manifest:manifest@localhost/manifest where
    manifest is the basename of the mandatory parameter.
-n  Account name for the admin account, defaults to superadmin
-p  Password for the admin account, defaults to password
-m  The mysql root user:password, this will default to root:$MYSQL_ROOTPASS
-d  Delete and overwrite, don't backup existing files
-t  The deployment target locally, defaults to minifest
-w  Working copy, include .git folder in the modules
-v  Be verbose (adds a set -x to the main script)
-b  Prepare a branch test.  This will make the value -u to use the specified
    value as the db details and target.  e.g. -b ch14 is the same as -t ch14 
    -u mysql://ch14:ch14@localhost/ch14 -w
    If both -b and -u/-t are specified the the -u/-t will override the -b

Sample manifest file:

makefile=http://192.168.21.27/manifest/wightlocations.make
remoteUrl=root@192.168.21.44
remotePath=/home/wightlocations/www/NeonTABS/demosite
profile=neontabs_profile
sitename="White Locations"
settings_module=ntch

N.B. No spaces between names, equals and values.  Quotes around sitename

EOF
    exit 1
fi

while getopts "u:n:p:m:t:b:wdv" options; do
    case $options in
        u)  dburl="$OPTARG";;
        n)  accountname="$OPTARG";;
        p)  accountpass="$OPTARG";;
        m)  mysqlroot="$OPTARG";;
        m)  delete="1";;
        t)  target="$OPTARG";;
        w)  wc="--working-copy";;
        v)  verbose="-v";;
        b)  branch="$OPTARG";;
    esac
done

shift $((OPTIND-1))
manifest=$1
_manifest=`basename $manifest .manifest`

if [ -z $manifest ]
then
    echo $USAGE
    exit 1
fi

if [ -z "$dburl" ]; then
    if [ ! -z "$branch" ]; then
        dburl="mysql://$branch:$branch@localhost/$branch"
    else
        dburl="mysql://$_manifest:$_manifest@localhost/$_manifest"
    fi
fi

if [ -z "$dburl" ]; then
    dburl="mysql://$_manifest:$_manifest@localhost/$_manifest"
fi

if [ -z "$accountname" ]; then
    accountname="superadmin"
fi

if [ -z "$accountpass" ]; then
    accountpass="password"
fi

if [ -z "$mysqlroot" ]; then
    mysqlrootuser=root
    mysqlrootpass=$MYSQL_ROOTPASS
else
    mysqlrootuser=`echo $mysqlroot | awk -F: '{print $1}'`
    mysqlrootpass=`echo $mysqlroot | awk -F: '{print $2}'`
fi

if [ -z "$mysqlrootpass" ]; then
    echo -ne "\x1b[33;01mMysql root password is not set, you have 5 seconds to abort \x1b[39;49;00m"
    for x in 1 2 3 4 5; do sleep 1; echo -n .; done; echo
fi

if [ -z "$target" ]; then
    if [ ! -z "$branch" ]; then
        target=$branch
    else
        target=$_manifest
    fi
fi

if [ ! -z "$verbose" ]; then
    echo -e "Remote Manifest:\t${manifest}";
    echo -e "Local Manifest:\t\t${_manifest}";
    echo -e "DB Url:\t\t\t${dburl}";
    echo -e "Account name:\t\t${accountname}";
    echo -e "Account password:\t${accountpass}";
    echo -e "Mysql root username:\t${mysqlrootuser}";
    echo -e "Mysql root password:\t${mysqlrootpass}";
    echo -e "Target dir:\t\t${target}";
    echo -e "Working copy:\t${wc}";

    set -x

fi

time=`date +"%y%m%d_%H-%M"`

if [ -f "$_manifest.manifest" ] && [ -z "$delete" ]; then
    mv $_manifest.manifest $_manifest.manifest.$time
else
    rm -rf "$_manifest.manifest"
fi
wget -q $manifest
source $_manifest.manifest

set +e
if [ -d "$target" ] && [ -z "$delete" ]; then
    mkdir -p $target/sites/default/sql
    if [ ! -e $target/sites/default/sql/.htaccess ]; then
        if [ -d /etc/apache2/conf-enabled ]; then
            # Cheap way of testing for apache 2.4 on ubuntu, unreliable but it works
            echo 'Require all denied' > $target/sites/default/sql/.htaccess
        else
            echo 'Order Deny Allow' > $target/sites/default/sql/.htaccess
            echo 'Deny from All' > $target/sites/default/sql/.htaccess
        fi
    fi
    drush -r $target cc all
    drush -r $target sql-dump > $sqlfile
    mv $target $target.$time
else
    rm -rf $target
fi
set -e

drush --nocolor make $wc $makefile $target
CWD=`pwd`
cd $CWD/$target
drush --nocolor -y si $profile --db-url=$dburl --account-name=$accountname --account-pass=$accountpass --db-su=$mysqlrootuser --db-su-pw=$mysqlrootpass --site-name="${sitename}"

drush cc all
drush en -y $settings_module

if [ ! -z "$remoteUrl" ]; then
    sqlfile=/tmp/$_manifest-dump.sql
    ssh $remoteUrl drush -r $remotePath cc all
    ssh $remoteUrl drush -r $remotePath --gzip sql-dump > ${sqlfile}.gz
    gzip -d ${sqlfile}.gz
    drush sqlq "source $sqlfile"
    rm $sqlfile
    if [ ! -z "$verbose" ]; then
        progress=" --progress "
    fi
    rsync --delete -az --exclude="files/tabs-imagecache" $progress $remoteUrl:$remotePath/sites/default/files sites/default
    drush cc all
fi

# Robots.txt
if [ ! -z "$robots" ]; then
    wget -O robots.txt $robots
else
    # Assume a dev site
    cat >robots.txt<<EOF
User-agent: *
Disallow: /
EOF
fi

# htaccess
if [ ! -z "$htaccess" ]; then
    wget -O .htaccess $htaccess
fi

set +e
for x in sites/all/themes/*; do
    if [ -d $CWD/$x ]; then
        cd $CWD/$x
        compass compile
        cd -
    fi
done
set -e


cd $CWD

if [ ! -z "$verbose" ]; then
    set +x
fi
