#!/bin/bash

NO_ARGS=0
USAGE="`basename $0` [-u dburl] [-n accountname] [-p accountpass] [-m mysqlroot] [-t target] manifest"

if [ $# -eq "$NO_ARGS" ]  # Script invoked with no command-line args?
then
    echo $USAGE
    cat <<EOF
Clones a remote drupal site providing it has been created using a make file
and profile.

The only mandatory parameter is the manifest location.  This must be a valid
URL.

-u  The DB url to create for this site, mysql://name:passwd@host/dbname this
    will default to the mysql://manifest:manifest@localhost/manifest where
    manifest is the basename of the mandatory parameter.
-n  Account name for the admin account, defaults to superadmin
-p  Password for the admin account, defaults to password
-m  The mysql root user:password, this will default to root:$MYSQL_ROOTPASS
-t  The deployment target locally, defaults to minifest
-w  Working copy, include .git folder in the modules
-v  Be verbose (adds a set -x to the main script)

Sample manifest file:

makefile=http://192.168.21.27/manifest/wightlocations.make
remoteUrl=root@192.168.21.44
remotePath=/home/wightlocations/www/NeonTABS/demosite
profile=neontabs_profile
sitename="White Locations"
settings_module=ntch

N.B. No spaces between names, equals and values.  Quotes around sitename

EOF
    exit 1
fi

while getopts "u:n:p:m:t:wv" options; do
    case $options in
        u)  dburl="$OPTARG";;
        n)  accountname="$OPTARG";;
        p)  accountpass="$OPTARG";;
        m)  mysqlroot="$OPTARG";;
        t)  target="$OPTARG";;
        w)  wc="--working-copy";;
        v)  verbose="-v";;
    esac
done

shift $((OPTIND-1))
manifest=$1
_manifest=`basename $manifest .manifest`

if [ -z $manifest ]
then
    echo $USAGE
    exit 1
fi

if [ -z "$dburl" ]; then
    dburl="mysql://$_manifest:$_manifest@localhost/$_manifest"
fi

if [ -z "$accountname" ]; then
    accountname="superadmin"
fi

if [ -z "$accountpass" ]; then
    accountpass="password"
fi

if [ -z "$mysqlroot" ]; then
    mysqlrootuser=root
    mysqlrootpass=$MYSQL_ROOTPASS
else
    mysqlrootuser=`echo $mysqlroot | awk -F: '{print $1}'`
    mysqlrootpass=`echo $mysqlroot | awk -F: '{print $2}'`
fi

if [ -z "$mysqlrootpass" ]; then
    echo -ne "\x1b[33;01mMysql root password is not set, you have 5 seconds to abort \x1b[39;49;00m"
    for x in 1 2 3 4 5; do sleep 1; echo -n .; done; echo
fi

if [ -z "$target" ]; then
    target=$_manifest
fi

if [ ! -z "$verbose" ]; then
    echo -e "Remote Manifest:\t${manifest}";
    echo -e "Local Manifest:\t\t${_manifest}";
    echo -e "DB Url:\t\t\t${dburl}";
    echo -e "Account name:\t\t${accountname}";
    echo -e "Account password:\t${accountpass}";
    echo -e "Mysql root username:\t${mysqlrootuser}";
    echo -e "Mysql root password:\t${mysqlrootpass}";
    echo -e "Target dir:\t\t${target}";

    set -x

fi

time=`date +"%y%m%d_%H-%M"`

if [ -f "$_manifest.manifest" ]; then
    mv $_manifest.manifest $_manifest.manifest.$time
fi
wget -q $manifest
source $_manifest.manifest

if [ -d "$target" ]; then
    mv $target $target.$time
fi

drush make $wc $makefile $target
CWD=`pwd`
cd $target
drush -y si $profile --db-url=$dburl --account-name=$accountname --account-pass=$accountpass --db-su=$mysqlrootuser --db-su-pw=$mysqlrootpass --site-name="${sitename}"

for x in `find sites/all/themes -type d -maxdepth 1`; do
    cd $x
    compass compile
    cd -
done

drush cc all
drush en -y $settings_module

if [ ! -z "$remoteUrl" ]; then
    ssh $remoteUrl drush -r $remotePath sql-dump > dump.sql
    drush sqlq "source dump.sql"
    rsync --delete -a $remoteUrl:$remotePath/sites/default/files sites/default
    drush cc all
fi

cd $CWD

if [ ! -z "$verbose" ]; then
    set +x
fi
