#!/bin/bash

set -e

CWD=`dirname $0`/..

USAGE="$0 [-h] [-p path] [-y drupaluser drupalgroup webuser webgroup]"

function help
{
    echo $USAGE
    cat <<EOF

This script will reset ownership and permissions on the drupal stack.  It will
try and guess the correct users and groups but may be run in a uninteractive
mode.  If run in non-interactive mode the you must pass the correct users and
groups to the script on the command line.  If you can't figure out how to use
the script with these instructions you are probably too stupid to have sudo/root
access which, incedentaly, you will need to run this script.

  -h Show this message
  -y Run non interactive, you will need to pass the users and groups
  -p The root of the drupal to reset

EOF
}

_user=$SUDO_USER
_root="$(id -u)"

while getopts "yhp:" options; do
  case $options in
    y)  NONINTER=1;;
    h)  help; exit 0;;
    p)  CWD="$OPTARG";;
  esac
done

if [ -z "$_user" ] && [ "$(id -u)" != "0" ]; then
    echo "You must run this script as root or using sudo"
    exit 1
fi

if [ "$NONINTER" == 1 ]; then
    shift $((OPTIND-1))
    druser=$1
    shift $((OPTIND-1))
    drgroup=$1
    shift $((OPTIND-1))
    webuser=$1
    shift $((OPTIND-1))
    webgroup=$1
else
    
    druser=$_user
    drgroup=users
    webuser=`grep 'www-data\|apache\|httpd\|http' /etc/passwd`
    webuser=`echo "$webuser"|awk -F : '{print $1}' | head -n 1`
    webgroup=`grep 'www-data\|apache\|httpd\|http' /etc/group`
    webgroup=`echo "$webgroup"|awk -F : '{print $1}'`

    until [ "$a" == 'y' ]; do
        echo
        echo -n "Enter the user name for the drupal user [$druser] "
        read input
        if [ ! -z "$input" ]; then
            druser=${input//[^a-zA-Z0-9]/}
        fi
    
        echo -n "Enter the group name for the drupal group [$drgroup] "
        read input
        if [ ! -z "$input" ]; then
            drgroup=${input//[^a-zA-Z0-9]/}
        fi
    
        echo -n "Enter the user name for the webuser [$webuser] "
        read input
        if [ ! -z "$input" ]; then
            webuser=${input//[^-a-zA-Z0-9]/}
        fi
    
        echo -n "Enter the user name for the webgroup [$webgroup] "
        read input
        if [ ! -z "$input" ]; then
            webgroup=${input//[^-a-zA-Z0-9]/}
        fi

        a=n
        echo
        echo "drupal user name = $druser"
        echo "drupal group name = $drgroup "
        echo "Webuser group name = $webuser"
        echo "Webgroup group name = $webgroup"
        echo
        echo -n "Proceed (Y/n)"
        read a
        if [ -z "$a" ]; then
            a=y
        fi
    done
fi

if [ -z "$druser" ]; then
    echo "drupal user not set, aborting"
    echo $USAGE
    exit 2;
fi

if [ -z "$drgroup" ]; then
    echo "drupal group not set, aborting"
    echo $USAGE
    exit 3;
fi

if [ -z "$webuser" ]; then
    echo "Web not set, aborting"
    echo $USAGE
    exit 4;
fi

if [ -z "$webgroup" ]; then
    echo "Web not set, aborting"
    echo $USAGE
    exit 5;
fi

setfacl=`which setfacl`
if [ -z "$setfacl" ]; then
    cat << EOF

I am unable to find the setfacl command.  To get permissions
to work both for the $webuser and $druser I would like to use
setfacl.  Without this I will set the permissions on the files

  $CWD/app/{logs,cache}

to be owned by the $webuser with the sticky bit set but you need
to add the $druser to the $webgroup and alter the apache umask
to 0002.

I recommend you install setfacl and remount the folder

  $CWD

with the acl flag:

  mount -o remount,acl /

Use ctrl-c to exit this script and install setfacl or hit any
key to continue.

EOF
    read
fi

echo druser  = $druser
echo drgroup = $drgroup
echo webuser = $webuser
echo webgroup = $webgroup
echo drupal dir = $CWD

set -x

find . ! -name . -prune -type d -exec chmod 775 {} \;
find . ! -name . -prune -type f -exec chmod 664 {} \;

chown -R $druser:$drgroup $CWD
chown -R $webuser:$webgroup $CWD/sites/*/files

chown a-w $CWD/sites/*/settings.php

if [ -z "$setfacl" ]; then
    find . ! -name . -prune -type d -exec chmod 1775 {} \;
    find . ! -name . -prune -type f -exec chmod 1664 {} \;
else
    sudo setfacl -R  -m   u:$webuser:rwx -m u:$druser:rwx -m g:$drgroup:rwx $CWD/sites/*/files
    sudo setfacl -dR -m   u:$webuser:rwx -m u:$druser:rwx -m g:$drgroup:rwx $CWD/sites/*/files
    sudo setfacl -R  -m d:u:$webuser:rwx -m u:$druser:rwx -m g:$drgroup:rwx $CWD/sites/*/files
fi

set +x

set +e
