#!/bin/bash

ESC_SEQ="\x1b["
COL_RESET=$ESC_SEQ"39;49;00m"
COL_RED=$ESC_SEQ"31;01m"
COL_GREEN=$ESC_SEQ"32;01m"
COL_YELLOW=$ESC_SEQ"33;01m"
COL_BLUE=$ESC_SEQ"34;01m"
COL_MAGENTA=$ESC_SEQ"35;01m"
COL_CYAN=$ESC_SEQ"36;01m"

set -e

USAGE="$0 /path/to/drupal version"

# Versions must not start with a letter, v1.0.0 bad 1.0.0.RC01 ok

DRUPAL_ROOT=$1
VERSION=$2

if [ -z "$DRUPAL_ROOT" ]; then
    echo $USAGE
    echo You must specify the path to the drupal root folder
    exit 1
fi

if [ -z "$VERSION" ]; then
    echo $USAGE
    echo You must specify a version number
    exit 1
fi

PACKAGE_NAME=`basename $DRUPAL_ROOT`

if [ ! -d "$DRUPAL_ROOT/sites/default/sql" ]; then
    chmod 755 ${DRUPAL_ROOT}/sites/default
    mkdir -p ${DRUPAL_ROOT}/sites/default/sql
    chmod 555 ${DRUPAL_ROOT}/sites/default
    APACHE_VERSION=`apache2ctl -v|head -n 1|cut -c 24-26`
    if [ "$APACHE_VERSION" == "2.4" ]; then
        cat >${DRUPAL_ROOT}/sites/default/sql/.htaccess<<EOF
Require all denied
EOF
    elif [ "$APACHE_VERSION" == "2.2" ]; then
        cat >${DRUPAL_ROOT}/sites/default/sql/.htaccess<<EOF
Order deny,allow
Deny from all
EOF
    else
        echo -e "${COL_RED}Unable to determine apache version.  I can create a .htaccess file in"
        echo -e "${DRUPAL_ROOT}/sites/default/sql/.htaccess.  You will need to create this yourself"
        echo -e "and re-run this script.${COL_RESET}"
    fi

fi

drush -r $DRUPAL_ROOT sql-dump --ordered-dump --result-file=sites/default/sql/site.sql  --structure-tables-key=common

mkdir -p $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
# cp -r $DRUPAL_ROOT $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
# tar & gzip the site.  the packager can't handle .info files
CWD=`pwd`
cd $DRUPAL_ROOT
tar -zcf ${CWD}/${PACKAGE_NAME}/${PACKAGE_NAME}-${VERSION}/${PACKAGE_NAME}.tgz * .htaccess
cd -

cd $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
dh_make -c GPL -e ${PACKAGE_NAME}${VERSION}@neontribe.co.uk -n -s -i -y 

rm debian/*.{ex,EX}

# Add php dependancies that chef missed
sed -i -e '/^Depends:/ s/$/ php-apc, php5-gd, php5-curl, php5-mysql, php5-imagick, php5-memcache, php5-memcached, ruby-compass /' debian/control

cat >debian/install<<EOF
${PACKAGE_NAME}.tgz /var/www/html/${PACKAGE_NAME}-${VERSION}
EOF

user=`echo ${PACKAGE_NAME} | cut -c 1-4`
user=$user`echo ${VERSION}| sed -e "s/\./_/g"`

cat >debian/postinst<<EOF
#!/bin/bash

case "\$1" in
    configure)
        tar -C /var/www/html/${PACKAGE_NAME}-${VERSION} -zxf /var/www/html/${PACKAGE_NAME}-${VERSION}/${PACKAGE_NAME}.tgz
        # get root password
        echo "Enter the root password for your MySQL instance:"
        stty -echo
        read mysqlroot
        stty echo

        # drop user and db if exists
        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT USAGE ON *.* TO $user@localhost;"
        mysql -u root -p\$mysqlroot -h localhost -s -e "DROP USER $user@localhost;"
        mysql -u root -p\$mysqlroot -h localhost -s -e "DROP DATABASE IF EXISTS $user ;"

        # create db and user
        mysql -u root -p\$mysqlroot -h localhost -s -e "CREATE USER $user@localhost IDENTIFIED BY '$user';"
        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT USAGE ON *.* TO $user@localhost IDENTIFIED BY '$user' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;"
        mysql -u root -p\$mysqlroot -h localhost -s -e "CREATE DATABASE IF NOT EXISTS $user ;"
        mysql -u root -p\$mysqlroot -h localhost -s -e "GRANT ALL PRIVILEGES ON $user.* TO $user@localhost;"

        # echo inport db
        mysql -u root -p\$mysqlroot -h localhost $user < /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/sql/site.sql

        # update settings.php
        chmod 666 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
        chmod 777 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default
        sed -i "s/      'database' => .*/      'database' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
        sed -i "s/      'username' => .*/      'username' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
        sed -i "s/      'password' => .*/      'password' => '$user',/g" /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
        chmod 444 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default/settings.php
        chmod 555 /var/www/html/${PACKAGE_NAME}-${VERSION}/sites/default

        echo "<VirtualHost *:80>" > /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  ServerAdmin webmaster@localhost" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  DocumentRoot /var/www/html/${PACKAGE_NAME}-${VERSION}" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  ErrorLog /var/log/apache2/error.log" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  CustomLog /var/log/apache2/access.log combined" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  <Directory /var/www/html/${PACKAGE_NAME}-${VERSION}>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "    AllowOverride All" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf
        echo "</VirtualHost>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-24.conf

        echo "<VirtualHost *:80>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  ServerAdmin webmaster@localhost" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  DocumentRoot /var/www/html/${PACKAGE_NAME}-${VERSION}" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  <Directory />" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    Options FollowSymLinks" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    AllowOverride None" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  <Directory /var/www/html/${PACKAGE_NAME}-${VERSION}>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    Options Indexes FollowSymLinks MultiViews" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    AllowOverride All" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    Order allow,deny" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "    allow from all" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  </Directory>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  ErrorLog /var/log/apache2/error.log" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  LogLevel warn" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "  CustomLog /var/log/apache2/access.log combined" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
        echo "</VirtualHost>" >> /etc/apache2/sites-available/${PACKAGE_NAME}-${VERSION}-22.conf
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
EOF

cd - && cd $PACKAGE_NAME/$PACKAGE_NAME-$VERSION
debuild -b -i -us -uc
