; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.27"

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_profile][download][type] = "git"
projects[neontabs_profile][download][url] = "http://192.168.21.27/repos/neontabs_profile/.git"
projects[neontabs_profile][type] = "profile"

projects[ctools][subdir] = "contrib"
projects[ctools][version] = "1.4"

projects[cacheexclude][subdir] = "contrib"
projects[cacheexclude][version] = "2.3"

projects[entity][subdir] = "contrib"
projects[entity][version] = "1.5"

projects[field_group][subdir] = "contrib"
projects[field_group][version] = "1.3"

projects[globalredirect][subdir] = "contrib"
projects[globalredirect][version] = "1.5"

projects[google_analytics][subdir] = "contrib"
projects[google_analytics][version] = "1.4"

projects[jquery_update][subdir] = "contrib"
projects[jquery_update][version] = "2.4"

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.2"

projects[link][subdir] = "contrib"
projects[link][version] = "1.2"

projects[menu_block][subdir] = "contrib"
projects[menu_block][version] = "2.3"

projects[menu_expanded][subdir] = "contrib"
projects[menu_expanded][version] = "1.0-beta1"

projects[metatag][subdir] = "contrib"
projects[metatag][version] = "1.0-beta9"

projects[references][subdir] = "contrib"
projects[references][version] = "2.1"

projects[pathauto][subdir] = "contrib"
projects[pathauto][version] = "1.2"

projects[redirect][subdir] = "contrib"
projects[redirect][version] = "1.0-rc1"

projects[site_map][subdir] = "contrib"
projects[site_map][version] = "1.2"

projects[smtp][subdir] = "contrib"
projects[smtp][version] = "1.0"

projects[tagclouds][subdir] = "contrib"
projects[tagclouds][version] = "1.9"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

projects[views][subdir] = "contrib"
projects[views][version] = "3.7"

projects[webform][subdir] = "contrib"
projects[webform][version] = "3.20"

projects[wysiwyg][subdir] = "contrib"
projects[wysiwyg][version] = "2.2"

projects[xmlsitemap][subdir] = "contrib"
projects[xmlsitemap][version] = "2.0"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_arealoc_page][download][type] = "git"
projects[neontabs_arealoc_page][download][url] = "http://192.168.21.27/repos/neontabs_arealoc_page/.git"
projects[neontabs_arealoc_page][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_blog][download][type] = "git"
projects[neontabs_blog][download][url] = "http://192.168.21.27/repos/neontabs_blog/.git"
projects[neontabs_blog][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_carousel][download][type] = "git"
projects[neontabs_carousel][download][url] = "http://192.168.21.27/repos/neontabs_carousel/.git"
projects[neontabs_carousel][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_comments][download][type] = "git"
projects[neontabs_comments][download][url] = "http://192.168.21.27/repos/neontabs_comments/.git"
projects[neontabs_comments][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_cust_wightloc][download][type] = "git"
projects[neontabs_cust_wightloc][download][url] = "http://192.168.21.27/repos/neontabs_cust_wightloc/.git"
projects[neontabs_cust_wightloc][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_featured_image_link][download][type] = "git"
projects[neontabs_featured_image_link][download][url] = "http://192.168.21.27/repos/neontabs_featured_image_link/.git"
projects[neontabs_featured_image_link][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_funcunit][download][type] = "git"
projects[neontabs_funcunit][download][url] = "http://192.168.21.27/repos/neontabs_funcunit/.git"
projects[neontabs_funcunit][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_glance][download][type] = "git"
projects[neontabs_glance][download][url] = "http://192.168.21.27/repos/neontabs_glance/.git"
projects[neontabs_glance][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_homepage_sidebar][download][type] = "git"
projects[neontabs_homepage_sidebar][download][url] = "http://192.168.21.27/repos/neontabs_homepage_sidebar/.git"
projects[neontabs_homepage_sidebar][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_image_attributes][download][type] = "git"
projects[neontabs_image_attributes][download][url] = "http://192.168.21.27/repos/neontabs_image_attributes/.git"
projects[neontabs_image_attributes][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_menus][download][type] = "git"
projects[neontabs_menus][download][url] = "http://192.168.21.27/repos/neontabs_menus/.git"
projects[neontabs_menus][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_permissions][download][type] = "git"
projects[neontabs_permissions][download][url] = "http://192.168.21.27/repos/neontabs_permissions/.git"
projects[neontabs_permissions][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_property_highlights][download][type] = "git"
projects[neontabs_property_highlights][download][url] = "http://192.168.21.27/repos/neontabs_property_highlights/.git"
projects[neontabs_property_highlights][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_property_info][download][type] = "git"
projects[neontabs_property_info][download][url] = "http://192.168.21.27/repos/neontabs_property_info/.git"
projects[neontabs_property_info][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_search][download][type] = "git"
projects[neontabs_search][download][url] = "http://192.168.21.27/repos/neontabs_search/.git"
projects[neontabs_search][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_selectlists][download][type] = "git"
projects[neontabs_selectlists][download][url] = "http://192.168.21.27/repos/neontabs_selectlists/.git"
projects[neontabs_selectlists][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_social][download][type] = "git"
projects[neontabs_social][download][url] = "http://192.168.21.27/repos/neontabs_social/.git"
projects[neontabs_social][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_teaser][download][type] = "git"
projects[neontabs_teaser][download][url] = "http://192.168.21.27/repos/neontabs_teaser/.git"
projects[neontabs_teaser][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_themer][download][type] = "git"
projects[neontabs_themer][download][url] = "http://192.168.21.27/repos/neontabs_themer/.git"
projects[neontabs_themer][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs_utility][download][type] = "git"
projects[neontabs_utility][download][url] = "http://192.168.21.27/repos/neontabs_utility/.git"
projects[neontabs_utility][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_areapages][download][type] = "git"
projects[tabs_areapages][download][url] = "http://192.168.21.27/repos/tabs_areapages/.git"
projects[tabs_areapages][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_balancepay][download][type] = "git"
projects[tabs_balancepay][download][url] = "http://192.168.21.27/repos/tabs_balancepay/.git"
projects[tabs_balancepay][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_booking][download][type] = "git"
projects[tabs_booking][download][url] = "http://192.168.21.27/repos/tabs_booking/.git"
projects[tabs_booking][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_entity][download][type] = "git"
projects[tabs_entity][download][url] = "http://192.168.21.27/repos/tabs_entity/.git"
projects[tabs_entity][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_gmap][download][type] = "git"
projects[tabs_gmap][download][url] = "http://192.168.21.27/repos/tabs_gmap/.git"
projects[tabs_gmap][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_imagecache2][download][type] = "git"
projects[tabs_imagecache2][download][url] = "http://192.168.21.27/repos/tabs_imagecache2/.git"
projects[tabs_imagecache2][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_io][download][type] = "git"
projects[tabs_io][download][url] = "http://192.168.21.27/repos/tabs_io/.git"
projects[tabs_io][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_landingpage][download][type] = "git"
projects[tabs_landingpage][download][url] = "http://192.168.21.27/repos/tabs_landingpage/.git"
projects[tabs_landingpage][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_query][download][type] = "git"
projects[tabs_query][download][url] = "http://192.168.21.27/repos/tabs_query/.git"
projects[tabs_query][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_search][download][type] = "git"
projects[tabs_search][download][url] = "http://192.168.21.27/repos/tabs_search/.git"
projects[tabs_search][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_shortlist][download][type] = "git"
projects[tabs_shortlist][download][url] = "http://192.168.21.27/repos/tabs_shortlist/.git"
projects[tabs_shortlist][type] = "module"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[tabs_sitemap][download][type] = "git"
projects[tabs_sitemap][download][url] = "http://192.168.21.27/repos/tabs_sitemap/.git"
projects[tabs_sitemap][type] = "module"

; Themes
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[neontabs][download][type] = "git"
projects[neontabs][download][url] = "http://192.168.21.27/repos/neontabs/.git"
projects[neontabs][type] = "theme"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[ntwl][download][type] = "git"
projects[ntwl][download][url] = "http://192.168.21.27/repos/neontabs_cust_wightloc_theme/.git"
projects[ntwl][type] = "theme"

; Libraries
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[tabs-api-client][download][type] = "git"
libraries[tabs-api-client][download][url] = "https://ntcsdl:b191wkm@github.com/CarltonSoftware/tabs-api-client.git"
libraries[tabs-api-client][directory_name] = "tabs-api-client"
libraries[tabs-api-client][type] = "library"

; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[ckeditor][download][type] = "file"
libraries[ckeditor][download][url] = "http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.6.6.1/ckeditor_3.6.6.1.zip"
libraries[ckeditor][directory_name] = "ckeditor"
libraries[ckeditor][type] = "library"

